--- #YAML:1.0
name:               Smart-Comments
version:            1.000004
abstract:           Comments that do more than just sit there
author:
    - Damian Conway <DCONWAY@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:    0
    Filter::Simple:  0
    List::Util:      0
    Test::More:      0
    Text::Balanced:  0
    version:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
